project:
  type: website
  resources: 
  - shinylive-sw.js
execute: 
  freeze: auto
website:  
  repo-url: https://github.com/emr65df/r-shinylive-demo
  repo-actions: [edit, issue]
  title: "r-shinylive in Quarto"
  navbar:
    search: false
    left:
      - text: "Previous Demo Code"
        file: index.qmd
      - text: "My Demo Code"
        file: R-shinylive-demo.qmd
      - text: "Future Demo"
        file: future-r-shinylive.qmd

format:
  html:
    grid: 
      body-width: 1350px
      sidebar-width: 200px
      margin-width: 200px
    toc: true

